services:
  - type: web
    name: video-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 300 app_proxy:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
    disk:
      name: video-storage
      mountPath: /app/downloads
      sizeGB: 1
